# Generated by Django 5.0.6 on 2024-06-06 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NetflixApp', '0002_alter_movie_genre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='desciption',
            new_name='description',
        ),
    ]
